apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      tls: false
      username: soc_user
      defaultDatabase: soc
    secureJsonData:
      password: changeme
