#!/usr/bin/env python3
"""
SOC Report Generator — query ClickHouse and produce an executive summary.

Requires: clickhouse-driver (pip install clickhouse-driver)

Usage:
  python report-generator.py --hours 24
  python report-generator.py --hours 168 --output report.md
"""

import argparse
import sys
from datetime import datetime

try:
    from clickhouse_driver import Client
except ImportError:
    print("Install clickhouse-driver: pip install clickhouse-driver")
    sys.exit(1)

CLICKHOUSE_HOST = "localhost"
CLICKHOUSE_USER = "soc_user"
CLICKHOUSE_PASSWORD = "changeme"
CLICKHOUSE_DB = "soc"


def parse_args():
    parser = argparse.ArgumentParser(description="Generate SOC summary report from ClickHouse")
    parser.add_argument("--hours", type=int, default=24, help="Lookback period in hours")
    parser.add_argument("--output", default=None, help="Output file (default: stdout)")
    return parser.parse_args()


def query(client, sql):
    return client.execute(sql)


def generate():
    args = parse_args()
    client = Client(
        host=CLICKHOUSE_HOST,
        user=CLICKHOUSE_USER,
        password=CLICKHOUSE_PASSWORD,
        database=CLICKHOUSE_DB,
    )

    window = f"now() - INTERVAL {args.hours} HOUR"

    total_alerts = query(client, f"""
        SELECT count() FROM soc.suricata_alerts
        WHERE timestamp > {window}
    """)[0][0]

    severity_breakdown = query(client, f"""
        SELECT alert_severity, count()
        FROM soc.suricata_alerts
        WHERE timestamp > {window}
        GROUP BY alert_severity ORDER BY alert_severity
    """)

    top_signatures = query(client, f"""
        SELECT alert_signature, count() AS cnt
        FROM soc.suricata_alerts
        WHERE timestamp > {window}
        GROUP BY alert_signature ORDER BY cnt DESC LIMIT 10
    """)

    top_sources = query(client, f"""
        SELECT src_ip, count() AS cnt
        FROM soc.suricata_alerts
        WHERE timestamp > {window}
        GROUP BY src_ip ORDER BY cnt DESC LIMIT 10
    """)

    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    report = f"""# SOC Executive Summary
**Generated:** {now}
**Period:** Last {args.hours} hours

---

## Overview
- **Total Alerts:** {total_alerts}

## Severity Breakdown
| Severity | Count |
|----------|-------|
"""
    for sev, cnt in severity_breakdown:
        label = {1: "High", 2: "Medium", 3: "Low"}.get(sev, str(sev))
        report += f"| {label} | {cnt} |\n"

    report += "\n## Top Alert Signatures\n| Signature | Count |\n|-----------|-------|\n"
    for sig, cnt in top_signatures:
        report += f"| {sig} | {cnt} |\n"

    report += "\n## Top Source IPs\n| Source IP | Count |\n|-----------|-------|\n"
    for ip, cnt in top_sources:
        report += f"| {ip} | {cnt} |\n"

    report += "\n---\n*Report auto-generated by SOC Report Generator*"

    if args.output:
        with open(args.output, "w") as f:
            f.write(report)
        print(f"Report written to {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    generate()
